baseURL = "http://uekoetter.dev/"
languageCode = "de-de"
title = "Jonas"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true

[params]
  author = "Jonas UekÃ¶tter"
  description = ""
  title = "Jonas UekÃ¶tter"
  favicon = "https://uekoetter.dev/favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "Â© 2021"

# socials can be found in header.html
[menu]  
  [[menu.main]]
    name = "ğŸ“ Blog"
    url = "/blog"
    weight = 1

  [[menu.main]]
    name = "â¤ï¸ Donate"
    url = "/donate"
    weight = 1

  [[menu.main]]
    name = "ğŸ“¦ OSS"
    url = "/dashboard"
    weight = 1


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true